version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_app
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_db
    ports:
      - "5001:5001"
    depends_on:
      - db
    command: npm run start

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432
volumes:
  db_data:
